#mongodb://note:note@localhost:27017
version: '3'
services:
  app:
    build:
      context: .
    image: yarinlaniado/noteapp
    ports:
      - "8080:8000"
    depends_on:
      - mongodb
    links:
      - mongodb 
  mongodb:
    image: mongo:7.0-rc-jammy
    container_name: my-mongodb-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: note
      MONGO_INITDB_ROOT_PASSWORD: note
    volumes:
      - mongodb-data:/data/db
    
volumes:
  mongodb-data:
