name: CI/CD Pipeline
on:
  push:
    branches:
      - yarin-cicd
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          ls -last
          pip install -r requirements.txt
      - name: Docker-compose up before tests
        run: |
          docker-compose -f testing-compose.yml up -d
      - name: Run Tests
        id: test
        run: |
          python3 app/test.py
      - name: Push Docker image to DockerHub
        if: steps.test.outcome == 'success'
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${{github.run_number}}"
          docker tag ${{secrets.DOCKER_IMAGE_NAME }}:latest "$IMAGE_NAME"
          docker push "$IMAGE_NAME"
          docker push ${{secrets.DOCKER_IMAGE_NAME }}:latest
      - name: Clean up
        run: |
          docker stop note-app-container || true
          docker rm note-app-container || true
          docker rmi note-app || true
      - name: Deploy to EKS
        if: steps.test.outcome == 'success'
        run: |
          # Placeholder for deploying application to EKS

      - name: Notify on Test Failure
        if: steps.test.outcome != 'success'
        run: |
          echo "tests failed! check the workflow"





